name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./화물/pom.xml
          mvn clean package -f ./배송/pom.xml
          mvn clean package -f ./정산/pom.xml
          mvn clean package -f ./알림/pom.xml

      - name: Docker Build and push for 화물
        uses: docker/build-push-action@v4
        with:
          context: ./화물
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/화물:latest
            ghcr.io/${{ github.repository }}/화물:${{ github.ref_name }}
            
      - name: Docker Build and push for 배송
        uses: docker/build-push-action@v4
        with:
          context: ./배송
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/배송:latest
            ghcr.io/${{ github.repository }}/배송:${{ github.ref_name }}
            
      - name: Docker Build and push for 정산
        uses: docker/build-push-action@v4
        with:
          context: ./정산
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/정산:latest
            ghcr.io/${{ github.repository }}/정산:${{ github.ref_name }}
            
      - name: Docker Build and push for 알림
        uses: docker/build-push-action@v4
        with:
          context: ./알림
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/알림:latest
            ghcr.io/${{ github.repository }}/알림:${{ github.ref_name }}
            
